package main

import (
	"bytes"
	"text/template"

	"github.com/pkg/errors"
)

func newFile(packageName string) file {
	return file{Package: packageName}
}

type file struct {
	Package  string
	Criteria []string
}

func (f file) generate() (string, error) {
	content := `
// This file was generated by ultimate cli
package {{.Package | ToLower}}	
{{range .Criteria}}{{.}}{{end}}
	`

	tmpl, err := template.New("file").Funcs(funcMap).Parse(content)
	if err != nil {
		return "", errors.Wrap(err, "cannot generate file")
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, f); err != nil {
		return "", errors.Wrap(err, "cannot generate file")
	}

	return buf.String(), nil
}
